### ISSUE TITLE
18. Implement colour scheme

### ISSUE THREAD

**Issue by bajancode** [the-collab-lab/tcl-31-smart-shopping-list#44]
Implement colours suggested in issue: https://github.com/the-collab-lab/tcl-31-smart-shopping-list/issues/36

Review app and see if there are any "missed" areas for colour consistency, ie. the input fields may have grey or white backgrounds, ensure they are consistent if needed. Material UI should do most of that already but just in case.

If once the colours are up and they actually *don't* look as good as we'd expect them to, feel free to play around and make more tweaks and suggestions to possible colours, ensuring they are accessible 

Acceptance criteria:

- [ ] Proposed colours have been applied to checkboxes and radio buttons
- [ ] Text colouring is consistent (while most is black, there is some grey for placeholder text for example, ensure this is consistent)
- [ ]  Other elements which require colouring, if any, have been identified and use colours from the same palate for consistency 
- [ ] If the colours for some reason are not looking as clean together as we would like, other colours have been proposed and implemented, ensuring they are still accessible

**Comment by gabynr** [comment]
I can't see the code. Do you push your change ?

**Comment by bajancode** [comment]
I pushed it to this branch:

https://github.com/the-collab-lab/tcl-31-smart-shopping-list/tree/implement-color-scheme


Thanks!!

**Comment by bajancode** [comment]
Thanks @gabynr! In response to your question over in the typography issue: It's not that behaviour, it's all of their outlines go grey for a given colour if I change it to Material UI's shade which aligns with our colour scheme. Even if I haven't selected any items.

green[800] is the colour from the colour scheme, and I was able to add it to the Radio buttons.

But here is what happens if I uncomment those lines trying to use green[800] (I also just tried using a hex number here but it didn't work)

![image](https://user-images.githubusercontent.com/52695922/143518548-fb3ad05b-13a9-4290-8227-c0ca2833901f.png)

**Comment by gabynr** [comment]
I need to pull this branch, because I don't understand what happened, but I finish for today. I'm going to sleep. I'll check this for tomorrow night, please, wait for me.

**Comment by bajancode** [comment]
Okay I will wait! Though if we have office hours I'll see if I can get some
help with it!

**Comment by gabynr** [comment]
Ok. I have a question. Why didn't you take a color from material UI?. https://mui.com/customization/color/
because In the checklist we don't set the color fixed. the color is set by the function getClassName(item) and it returns the name of the color and in the checklist set the tone of the color (getClassName(item)[800]), for that reason we need to use the color from MateriaUI.

**Comment by bajancode** [comment]
The colours are from Material UI, that Andrea had picked out, ie. The green is the green[800].

The only that isn't is I changed the orange to be the same as the one Aidan used on the homepage because everyone liked how that looked already and the graphics were also chosen which worked with the colours he'd picked. But maybe we could change the welcome page main colours if it is too much hassle to customize here
