### ISSUE TITLE
20. Incorporate graphics

### ISSUE THREAD

**Issue by bajancode** [the-collab-lab/tcl-31-smart-shopping-list#45]
A few orange themed graphics have been proposed, let's get them in the app and looking pretty!

AC:
- [ ] Graphics used have been "cleaned up"  ie. backgrounds removed if needed, shadows added / removed, etc.
- [ ] Decide if any images (such as the single orange) should be a "logo" type image to be used on both pages, and incorporate it onto the pages 
- [ ] Decide which, if any background or photo is to be used on the List page, and where, and add to the page
- [ ] Decide which, if any, background or photo is to be used on the Welcome page, and add to the page (I think @aidantorrence has basically done this already)

**Comment by bajancode** [comment]
I will add that I think we could drop the "glasses" logo idea we had and stick with the oranges, so it's not too busy.

I'd also give my opinion that I love all the orange graphics proposed so far, except for the ones with the smiling people holding the oranges. I know we were trying for "fun" with them but they aren't my favourite...I think might be easier to stick just with non-human images, or if we did human/animal, then a drawing vs. a photo

**Comment by gabynr** [comment]
Great. I agree with you.

**Comment by bajancode** [comment]
I think we can close this as it was kind of done in the other issues!
